# 워크플로 이름 지정
name: CI

# 워크플로 시작 조건 지정 (트리거)
on:
  push:
    branches: [ master ]  # master 브랜치에 푸시할 때마다 워크플로 시작

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 지정
    steps:  # 실행 스텝 지정 (실행 스텝 그룹화)
      - uses: actions/checkout@v3 # actions/checkout@v3 라는 작업의 v3 버전 실행

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew  # 스텝 이름 지정
        run: chmod +x gradlew # 실행할 명령어

      - name: Build with Gradle
        run: ./gradlew clean build